pipeline {
    agent any

    stages {
        stage('Get Code') {
            steps {
                git branch: 'main', url: 'https://github.com/hughesjack07-wq/Jackspetitions.git'
            }
        }
        stage('Build') {
            steps {
                sh 'cd Jackspetitions && chmod +x mvnw && JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 ./mvnw clean package -DskipTests'
            }
        }
        stage('Test') {
            steps {
                sh 'cd Jackspetitions && JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 ./mvnw test'
            }
        }
        stage('Package & Archive') {
            steps {
                archiveArtifacts artifacts: 'Jackspetitions/target/jackspetitions.war', fingerprint: true
            }
        }
        stage('Deploy') {
            steps {
                input message: 'Deploy to production?', ok: 'Yes, deploy!'
                deploy adapters: [tomcat9(credentialsId: 'tomcat-credentials',
                        path: '',
                        url: 'http://13.48.249.160:9090')],
                        contextPath: 'jackspetitions',
                        war: 'Jackspetitions/target/jackspetitions.war'
            }
        }
    }
}